import { Actor } from "./actor.interface";
export interface MovieListDetail {
    id: number;
    title: string;
    description: string;
    year: string;
    rating: number;
    poster: string;
    backdrop: string;
    actors: Actor[];
}

/*{
    "adult": false,
    "backdrop_path": "/fqv8v6AycXKsivp1T5yKtLbGXce.jpg",
    "belongs_to_collection": {
        "id": 173710,
        "name": "El planeta de los simios (El origen) - Colección",
        "poster_path": "/4QUhVxQgtsUhqydkmrFob90Rtwl.jpg",
        "backdrop_path": "/2ZkvqfOJUCINozB00wmYuGJQW81.jpg"
    },
    "budget": 160000000,
    "genres": [
        {
            "id": 878,
            "name": "Ciencia ficción"
        },
        {
            "id": 12,
            "name": "Aventura"
        },
        {
            "id": 28,
            "name": "Acción"
        }
    ],
    "homepage": "",
    "id": 653346,
    "imdb_id": "tt11389872",
    "origin_country": [
        "US"
    ],
    "original_language": "en",
    "original_title": "Kingdom of the Planet of the Apes",
    "overview": "Ambientada varias generaciones en el futuro tras el reinado de César, en la que los simios son la especie dominante que vive en armonía y los humanos se han visto reducidos a vivir en la sombra. Mientras un nuevo y tiránico líder simio construye su imperio, un joven simio emprende un angustioso viaje que le llevará a cuestionarse todo lo que sabe sobre el pasado y a tomar decisiones que definirán el futuro de simios y humanos por igual.",
    "popularity": 6097.733,
    "poster_path": "/kkFn3KM47Qq4Wjhd8GuFfe3LX27.jpg",
    "production_companies": [
        {
            "id": 127928,
            "logo_path": "/h0rjX5vjW5r8yEnUBStFarjcLT4.png",
            "name": "20th Century Studios",
            "origin_country": "US"
        },
        {
            "id": 133024,
            "logo_path": null,
            "name": "Oddball Entertainment",
            "origin_country": "US"
        },
        {
            "id": 89254,
            "logo_path": null,
            "name": "Jason T. Reed Productions",
            "origin_country": "US"
        }
    ],
    "production_countries": [
        {
            "iso_3166_1": "US",
            "name": "United States of America"
        }
    ],
    "release_date": "2024-05-08",
    "revenue": 338039904,
    "runtime": 145,
    "spoken_languages": [
        {
            "english_name": "English",
            "iso_639_1": "en",
            "name": "English"
        }
    ],
    "status": "Released",
    "tagline": "",
    "title": "El reino del planeta de los simios",
    "video": false,
    "vote_average": 6.933,
    "vote_count": 783,
    "credits": {
        "cast": [
            {
                "adult": false,
                "gender": 2,
                "id": 1586047,
                "known_for_department": "Acting",
                "name": "Owen Teague",
                "original_name": "Owen Teague",
                "popularity": 29.636,
                "profile_path": "/tgCkGE0LIggyjMmgSwHhpZAkfJs.jpg",
                "cast_id": 9,
                "character": "Noa",
                "credit_id": "630449a821118f007d331afa",
                "order": 0
            },
            {
                "adult": false,
                "gender": 1,
                "id": 2146942,
                "known_for_department": "Acting",
                "name": "Freya Allan",
                "original_name": "Freya Allan",
                "popularity": 73.019,
                "profile_path": "/xq33JCqUjBzPz3drN48N2N7ySKI.jpg",
                "cast_id": 10,
                "character": "Nova / Mae",
                "credit_id": "6335d124982f74007b84e461",
                "order": 1
            },
            {
                "adult": false,
                "gender": 2,
                "id": 79072,
                "known_for_department": "Acting",
                "name": "Kevin Durand",
                "original_name": "Kevin Durand",
                "popularity": 67.07,
                "profile_path": "/hINvryvce5tpod6kTnUg9ZTH8wg.jpg",
                "cast_id": 21,
                "character": "Proximus Caesar",
                "credit_id": "633f5aec68afd6008e006926",
                "order": 2
            },
            {
                "adult": false,
                "gender": 2,
                "id": 1444816,
                "known_for_department": "Acting",
                "name": "Peter Macon",
                "original_name": "Peter Macon",
                "popularity": 44.489,
                "profile_path": "/jF4jzgtWB2NAJ6BfVTSDQOlOHLr.jpg",
                "cast_id": 11,
                "character": "Raka",
                "credit_id": "6335d18d8c22c000825bdddd",
                "order": 3
            },
            {
                "adult": false,
                "gender": 2,
                "id": 3905,
                "known_for_department": "Acting",
                "name": "William H. Macy",
                "original_name": "William H. Macy",
                "popularity": 34.993,
                "profile_path": "/hdVEGSrP8qWlJnt0v5vSVcGOjy7.jpg",
                "cast_id": 30,
                "character": "Trevathan",
                "credit_id": "63bf469705a5330094ee5a7f",
                "order": 4
            },
            {
                "adult": false,
                "gender": 2,
                "id": 966554,
                "known_for_department": "Acting",
                "name": "Eka Darville",
                "original_name": "Eka Darville",
                "popularity": 26.56,
                "profile_path": "/7tNdST92WSTGHmEJbExaRlQHWcW.jpg",
                "cast_id": 22,
                "character": "Sylva",
                "credit_id": "633f7296435011007afbd2b6",
                "order": 5
            },
            {
                "adult": false,
                "gender": 2,
                "id": 1394427,
                "known_for_department": "Acting",
                "name": "Travis Jeffery",
                "original_name": "Travis Jeffery",
                "popularity": 23.51,
                "profile_path": "/picKz6F5ZNpZeDF1oRXHpSR8V8w.jpg",
                "cast_id": 25,
                "character": "Anaya",
                "credit_id": "63588890c439c000831daeae",
                "order": 6
            },
            {
                "adult": false,
                "gender": 1,
                "id": 2435321,
                "known_for_department": "Acting",
                "name": "Lydia Peckham",
                "original_name": "Lydia Peckham",
                "popularity": 20.895,
                "profile_path": "/tcBJklZSsP2JuQIYataJHW3pJXE.jpg",
                "cast_id": 29,
                "character": "Soona",
                "credit_id": "635888b915959f0082a88903",
                "order": 7
            },
            {
                "adult": false,
                "gender": 2,
                "id": 136295,
                "known_for_department": "Acting",
                "name": "Neil Sandilands",
                "original_name": "Neil Sandilands",
                "popularity": 24.517,
                "profile_path": "/t0tWl640swPEEBd5mY51Xtekvuo.jpg",
                "cast_id": 26,
                "character": "Koro",
                "credit_id": "6358889630813100a3362f82",
                "order": 8
            },
            {
                "adult": false,
                "gender": 2,
                "id": 3757983,
                "known_for_department": "Acting",
                "name": "Ras-Samuel Welda'abzgi",
                "original_name": "Ras-Samuel Welda'abzgi",
                "popularity": 5.434,
                "profile_path": "/pZhLFFEjzbg5fEl53TgagusDGp1.jpg",
                "cast_id": 28,
                "character": "Lightning",
                "credit_id": "635888b12cefc2007d2bb060",
                "order": 9
            },
            {
                "adult": false,
                "gender": 1,
                "id": 103406,
                "known_for_department": "Acting",
                "name": "Sara Wiseman",
                "original_name": "Sara Wiseman",
                "popularity": 11.147,
                "profile_path": "/oZUbTYeLBywjNv6Ul1nZryFsffq.jpg",
                "cast_id": 27,
                "character": "Dar",
                "credit_id": "635888a22ceb530079797f15",
                "order": 10
            },
            {
                "adult": false,
                "gender": 2,
                "id": 2646671,
                "known_for_department": "Acting",
                "name": "Kaden Hartcher",
                "original_name": "Kaden Hartcher",
                "popularity": 8.889,
                "profile_path": "/4SbhcfR8yKTII0PAcNZDxczXN38.jpg",
                "cast_id": 49,
                "character": "Oda / Rust",
                "credit_id": "6647386cc0fa664adb25bbfa",
                "order": 11
            },
            {
                "adult": false,
                "gender": 2,
                "id": 78962,
                "known_for_department": "Acting",
                "name": "Andy McPhee",
                "original_name": "Andy McPhee",
                "popularity": 10.355,
                "profile_path": "/uC0QWuaaOoIcLl6f5ebkFgTyF1r.jpg",
                "cast_id": 48,
                "character": "Honored Elder",
                "credit_id": "6642c92888748c0ad6cb36c4",
                "order": 12
            },
            {
                "adult": false,
                "gender": 1,
                "id": 4472548,
                "known_for_department": "Acting",
                "name": "Nina Gallas",
                "original_name": "Nina Gallas",
                "popularity": 3.326,
                "profile_path": "/ymN3Ng8gB32DwlbWdFQqsuJeC4m.jpg",
                "cast_id": 40,
                "character": "Youngster #1",
                "credit_id": "663bc87663679ef9a0d8fbbf",
                "order": 13
            },
            {
                "adult": false,
                "gender": 2,
                "id": 2632353,
                "known_for_department": "Acting",
                "name": "Samuel Falé",
                "original_name": "Samuel Falé",
                "popularity": 4.876,
                "profile_path": "/1aZqQhJEPP2FVdFgvOJ7CLyZ7IO.jpg",
                "cast_id": 43,
                "character": "Youngster #2",
                "credit_id": "6640eb77340e9a9a7e36ecaf",
                "order": 14
            },
            {
                "adult": false,
                "gender": 1,
                "id": 94797,
                "known_for_department": "Acting",
                "name": "Dichen Lachman",
                "original_name": "Dichen Lachman",
                "popularity": 33.695,
                "profile_path": "/96RTQAmcdl16ouztMrv7T177EyC.jpg",
                "cast_id": 31,
                "character": "Korina",
                "credit_id": "63f04702a24c5000800b61ca",
                "order": 15
            },
            {
                "adult": false,
                "gender": 1,
                "id": 2637893,
                "known_for_department": "Acting",
                "name": "Virginie Laverdure",
                "original_name": "Virginie Laverdure",
                "popularity": 9.741,
                "profile_path": "/ujTTbrapu2km7ApWOIoYZn7IybZ.jpg",
                "cast_id": 58,
                "character": "Lead Tech",
                "credit_id": "664faff3ada1c928b24f8a21",
                "order": 16
            },
            {
                "adult": false,
                "gender": 2,
                "id": 166703,
                "known_for_department": "Acting",
                "name": "Markus Hamilton",
                "original_name": "Markus Hamilton",
                "popularity": 8.079,
                "profile_path": "/7AgC90kPSOZmUkBIFrCvrkXSL8G.jpg",
                "cast_id": 59,
                "character": "Tech #1",
                "credit_id": "664fb006ddcc9a3defdd494c",
                "order": 17
            },
            {
                "adult": false,
                "gender": 0,
                "id": 2128650,
                "known_for_department": "Acting",
                "name": "Benjamin Scott",
                "original_name": "Benjamin Scott",
                "popularity": 5.224,
                "profile_path": null,
                "cast_id": 60,
                "character": "Tech #2",
                "credit_id": "664fb01637bccacfa04f89a4",
                "order": 18
            },
            {
                "adult": false,
                "gender": 0,
                "id": 3085693,
                "known_for_department": "Acting",
                "name": "Nirish Bhat Surambadka",
                "original_name": "Nirish Bhat Surambadka",
                "popularity": 2.572,
                "profile_path": null,
                "cast_id": 61,
                "character": "Youngster #3",
                "credit_id": "664fb037ed4fe8930495486e",
                "order": 19
            },
            {
                "adult": false,
                "gender": 1,
                "id": 2309880,
                "known_for_department": "Acting",
                "name": "Frances Berry",
                "original_name": "Frances Berry",
                "popularity": 10.948,
                "profile_path": "/qCp0psD5qzguABpRxWmMuC04kcl.jpg",
                "cast_id": 46,
                "character": "Laika",
                "credit_id": "6642c749c2014473a3349c41",
                "order": 20
            },
            {
                "adult": false,
                "gender": 2,
                "id": 4732041,
                "known_for_department": "Acting",
                "name": "Peter Hayes",
                "original_name": "Peter Hayes",
                "popularity": 0.426,
                "profile_path": null,
                "cast_id": 62,
                "character": "Feral Human #1",
                "credit_id": "664fb07147a89ad09d859d44",
                "order": 21
            },
            {
                "adult": false,
                "gender": 1,
                "id": 1745137,
                "known_for_department": "Acting",
                "name": "Sheree da Costa",
                "original_name": "Sheree da Costa",
                "popularity": 2.118,
                "profile_path": null,
                "cast_id": 63,
                "character": "Feral Human #2",
                "credit_id": "664fb07b76e4fb6e32ec1a54",
                "order": 22
            },
            {
                "adult": false,
                "gender": 0,
                "id": 4732042,
                "known_for_department": "Acting",
                "name": "Souleymane Diasse",
                "original_name": "Souleymane Diasse",
                "popularity": 0.357,
                "profile_path": null,
                "cast_id": 64,
                "character": "Feral Human #3",
                "credit_id": "664fb0925cc84de27b9b0b93",
                "order": 23
            },
            {
                "adult": false,
                "gender": 1,
                "id": 1445877,
                "known_for_department": "Acting",
                "name": "Olga Miller",
                "original_name": "Olga Miller",
                "popularity": 7.384,
                "profile_path": "/luRnZ3knzWnoRzZAv5x3wH0MJpr.jpg",
                "cast_id": 44,
                "character": "Feral Human #4",
                "credit_id": "6642c6d5683cbc9c7835b08b",
                "order": 24
            },
            {
                "adult": false,
                "gender": 2,
                "id": 581170,
                "known_for_department": "Acting",
                "name": "Дмитрий Миллер",
                "original_name": "Дмитрий Миллер",
                "popularity": 5.323,
                "profile_path": "/wuQSGEO26fJkIKGKaIxwd9dPIRZ.jpg",
                "cast_id": 45,
                "character": "Feral Human #5",
                "credit_id": "6642c6efb82ef8698d356705",
                "order": 25
            },
            {
                "adult": false,
                "gender": 1,
                "id": 4732043,
                "known_for_department": "Acting",
                "name": "Anastasia Miller",
                "original_name": "Anastasia Miller",
                "popularity": 0.357,
                "profile_path": null,
                "cast_id": 65,
                "character": "Feral Human #6",
                "credit_id": "664fb122a647645f51ec1f32",
                "order": 26
            },
            {
                "adult": false,
                "gender": 0,
                "id": 4732044,
                "known_for_department": "Acting",
                "name": "Michael Spudic",
                "original_name": "Michael Spudic",
                "popularity": 0.522,
                "profile_path": null,
                "cast_id": 66,
                "character": "Tech #3",
                "credit_id": "664fb140fd717346b4dd4cf5",
                "order": 27
            },
            {
                "adult": false,
                "gender": 1,
                "id": 58395,
                "known_for_department": "Acting",
                "name": "Karin Konoval",
                "original_name": "Karin Konoval",
                "popularity": 17.908,
                "profile_path": "/5e8YyNQjWre2UbExYBlJ7zva934.jpg",
                "cast_id": 41,
                "character": "Maurice (uncredited)",
                "credit_id": "663ce4273042f35be3fa6d42",
                "order": 28
            }
        ],
        "crew": [
            {
                "adult": false,
                "gender": 2,
                "id": 1179066,
                "known_for_department": "Directing",
                "name": "Wes Ball",
                "original_name": "Wes Ball",
                "popularity": 21.787,
                "profile_path": "/zVPXrhuAxYAWlwDEWCaqeUPycFx.jpg",
                "credit_id": "5de6f63611386c001354710d",
                "department": "Directing",
                "job": "Director"
            },
            {
                "adult": false,
                "gender": 2,
                "id": 91161,
                "known_for_department": "Production",
                "name": "Joe Hartwick Jr.",
                "original_name": "Joe Hartwick Jr.",
                "popularity": 4.309,
                "profile_path": null,
                "credit_id": "5de6f6f0cf4b8b00112791a3",
                "department": "Production",
                "job": "Producer"
            },
            {
                "adult": false,
                "gender": 2,
                "id": 266920,
                "known_for_department": "Production",
                "name": "Peter Chernin",
                "original_name": "Peter Chernin",
                "popularity": 6.656,
                "profile_path": "/6c7tilaP8n2bYJB0H6BZyEkd64k.jpg",
                "credit_id": "5e22a3288f26bc0015758ec5",
                "department": "Production",
                "job": "Executive Producer"
            },
            {
                "adult": false,
                "gender": 2,
                "id": 67802,
                "known_for_department": "Writing",
                "name": "Rick Jaffa",
                "original_name": "Rick Jaffa",
                "popularity": 13.111,
                "profile_path": "/iki2KpmMFhLIdq3pvHhq7tit8Q1.jpg",
                "credit_id": "6335d2a6cca7de007cd8f9b6",
                "department": "Production",
                "job": "Producer"
            },
            {
                "adult": false,
                "gender": 1,
                "id": 67803,
                "known_for_department": "Writing",
                "name": "Amanda Silver",
                "original_name": "Amanda Silver",
                "popularity": 17.734,
                "profile_path": "/j26E4ifZClUceVocOmDG9sWm7uP.jpg",
                "credit_id": "6335d2b6982f740080418fb5",
                "department": "Production",
                "job": "Producer"
            },
            {
                "adult": false,
                "gender": 2,
                "id": 100186,
                "known_for_department": "Production",
                "name": "Jason Reed",
                "original_name": "Jason Reed",
                "popularity": 4.872,
                "profile_path": null,
                "credit_id": "6335d2cb982f7400836afa00",
                "department": "Production",
                "job": "Producer"
            },
            {
                "adult": false,
                "gender": 1,
                "id": 36427,
                "known_for_department": "Production",
                "name": "Jenno Topping",
                "original_name": "Jenno Topping",
                "popularity": 11.293,
                "profile_path": "/tOti87QZZwyBp1iujzPTib9AwuU.jpg",
                "credit_id": "6335d2e02cde98007e413932",
                "department": "Production",
                "job": "Executive Producer"
            },
            {
                "adult": false,
                "gender": 2,
                "id": 19291,
                "known_for_department": "Art",
                "name": "Daniel T. Dorrance",
                "original_name": "Daniel T. Dorrance",
                "popularity": 4.486,
                "profile_path": null,
                "credit_id": "6335ded9fa78cd007cff3ecb",
                "department": "Art",
                "job": "Production Design"
            },
            {
                "adult": false,
                "gender": 2,
                "id": 30459,
                "known_for_department": "Camera",
                "name": "Pados Gyula",
                "original_name": "Pados Gyula",
                "popularity": 4.706,
                "profile_path": null,
                "credit_id": "63369d6bf8e982007c69efe8",
                "department": "Camera",
                "job": "Director of Photography"
            },
            {
                "adult": false,
                "gender": 2,
                "id": 6043,
                "known_for_department": "Editing",
                "name": "Dan Zimmerman",
                "original_name": "Dan Zimmerman",
                "popularity": 11.728,
                "profile_path": null,
                "credit_id": "634526972dffd8007a395a7b",
                "department": "Editing",
                "job": "Editor"
            },
            {
                "adult": false,
                "gender": 1,
                "id": 17675,
                "known_for_department": "Costume & Make-Up",
                "name": "Mayes C. Rubeo",
                "original_name": "Mayes C. Rubeo",
                "popularity": 3.623,
                "profile_path": "/zq3OHlYKVGPQd1gbojz3xY6t5pT.jpg",
                "credit_id": "6345272007e2810082f117d2",
                "department": "Costume & Make-Up",
                "job": "Costume Design"
            },
            {
                "adult": false,
                "gender": 2,
                "id": 67802,
                "known_for_department": "Writing",
                "name": "Rick Jaffa",
                "original_name": "Rick Jaffa",
                "popularity": 13.111,
                "profile_path": "/iki2KpmMFhLIdq3pvHhq7tit8Q1.jpg",
                "credit_id": "6544c03bfd4f80013ce7df7e",
                "department": "Writing",
                "job": "Characters"
            },
            {
                "adult": false,
                "gender": 1,
                "id": 67803,
                "known_for_department": "Writing",
                "name": "Amanda Silver",
                "original_name": "Amanda Silver",
                "popularity": 17.734,
                "profile_path": "/j26E4ifZClUceVocOmDG9sWm7uP.jpg",
                "credit_id": "6544c041fd4f80011ed002e5",
                "department": "Writing",
                "job": "Characters"
            },
            {
                "adult": false,
                "gender": 2,
                "id": 1179066,
                "known_for_department": "Directing",
                "name": "Wes Ball",
                "original_name": "Wes Ball",
                "popularity": 21.787,
                "profile_path": "/zVPXrhuAxYAWlwDEWCaqeUPycFx.jpg",
                "credit_id": "6544c05b9cc67b00df925d7d",
                "department": "Production",
                "job": "Producer"
            },
            {
                "adult": false,
                "gender": 2,
                "id": 1418397,
                "known_for_department": "Visual Effects",
                "name": "Erik Winquist",
                "original_name": "Erik Winquist",
                "popularity": 2.601,
                "profile_path": null,
                "credit_id": "6614bf94d18b24017c34da58",
                "department": "Visual Effects",
                "job": "Visual Effects Supervisor"
            },
            {
                "adult": false,
                "gender": 2,
                "id": 77949,
                "known_for_department": "Sound",
                "name": "John Paesano",
                "original_name": "John Paesano",
                "popularity": 9.948,
                "profile_path": "/pHQM6fGdewxwoqzTEMmHonX4KFz.jpg",
                "credit_id": "6614bfa233a533017d8699eb",
                "department": "Sound",
                "job": "Original Music Composer"
            },
            {
                "adult": false,
                "gender": 2,
                "id": 71148,
                "known_for_department": "Editing",
                "name": "Dirk Westervelt",
                "original_name": "Dirk Westervelt",
                "popularity": 5.075,
                "profile_path": null,
                "credit_id": "6614bfbe982f74017e60e079",
                "department": "Editing",
                "job": "Editor"
            },
            {
                "adult": false,
                "gender": 2,
                "id": 507,
                "known_for_department": "Writing",
                "name": "Josh Friedman",
                "original_name": "Josh Friedman",
                "popularity": 14.108,
                "profile_path": "/8zhRXGngBrijgBE3SDXxeOfbaOO.jpg",
                "credit_id": "6614c003e10f46016339a264",
                "department": "Writing",
                "job": "Writer"
            },
            {
                "adult": false,
                "gender": 1,
                "id": 1399313,
                "known_for_department": "Visual Effects",
                "name": "Julia Neighly",
                "original_name": "Julia Neighly",
                "popularity": 5.44,
                "profile_path": null,
                "credit_id": "664faed786f4b9ecd14f893b",
                "department": "Visual Effects",
                "job": "Visual Effects Producer"
            },
            {
                "adult": false,
                "gender": 0,
                "id": 1662726,
                "known_for_department": "Visual Effects",
                "name": "Patrick Neighly",
                "original_name": "Patrick Neighly",
                "popularity": 2.63,
                "profile_path": null,
                "credit_id": "664faee037bccacfa04f897e",
                "department": "Visual Effects",
                "job": "Visual Effects Producer"
            },
            {
                "adult": false,
                "gender": 1,
                "id": 495,
                "known_for_department": "Production",
                "name": "Debra Zane",
                "original_name": "Debra Zane",
                "popularity": 7.159,
                "profile_path": "/wiJJU7vSHNsW5HFkz2WX38Wg5xH.jpg",
                "credit_id": "664faf1ff38ca42077caf5b8",
                "department": "Production",
                "job": "Casting"
            },
            {
                "adult": false,
                "gender": 2,
                "id": 1660711,
                "known_for_department": "Production",
                "name": "Dylan Jury",
                "original_name": "Dylan Jury",
                "popularity": 10.424,
                "profile_path": "/qLiWkJ8jQh3yHkQ8eERSbxmB9OH.jpg",
                "credit_id": "664faf257d97c9231a9b0970",
                "department": "Production",
                "job": "Casting"
            },
            {
                "adult": false,
                "gender": 0,
                "id": 1412734,
                "known_for_department": "Production",
                "name": "Jennifer Cornwell",
                "original_name": "Jennifer Cornwell",
                "popularity": 1.639,
                "profile_path": null,
                "credit_id": "664faf6f8e516f0b7aec21ba",
                "department": "Production",
                "job": "Unit Production Manager"
            },
            {
                "adult": false,
                "gender": 0,
                "id": 2045537,
                "known_for_department": "Directing",
                "name": "Justin Muller",
                "original_name": "Justin Muller",
                "popularity": 4.57,
                "profile_path": null,
                "credit_id": "664faf7bb94d4acdcd4f8a7d",
                "department": "Directing",
                "job": "First Assistant Director"
            },
            {
                "adult": false,
                "gender": 0,
                "id": 86599,
                "known_for_department": "Directing",
                "name": "Jon Mallard",
                "original_name": "Jon Mallard",
                "popularity": 6.885,
                "profile_path": null,
                "credit_id": "664faf8248791d4e2d859cff",
                "department": "Directing",
                "job": "First Assistant Director"
            },
            {
                "adult": false,
                "gender": 0,
                "id": 1401734,
                "known_for_department": "Crew",
                "name": "Glenn Suter",
                "original_name": "Glenn Suter",
                "popularity": 2.836,
                "profile_path": null,
                "credit_id": "664faf8aa91c2b970add4f15",
                "department": "Crew",
                "job": "Stunt Coordinator"
            }
        ]
    }
}*/